name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main # Trigger workflow when changes are pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use your preferred Node.js version
          cache: 'npm'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Project
      - name: Build Project
        run: npm run build # This will create the dist directory

      # Step 5: Publish Dist Directory to Build Branch
      - name: Deploy to Build Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # Target branch for the built assets
          FOLDER: dist # Updated to point to the dist folder
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: {sha}'
