name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Main Branch
      - name: Checkout Main Branch
        uses: actions/checkout@v3

      # Step 2: Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Project
      - name: Build Project
        run: npm run build

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 6: Copy All Files to Build Branch
      - name: Copy Files Safely
        run: |
          if [ -d "./dist" ]; then
            cp -R ./dist/* ./
          else
            echo "Dist folder does not exist. Build process failed."
            exit 1
          fi

      # Step 7: Push Changes to Build Branch
      - name: Push Changes
        run: |
          git add .
          git commit -m "Deploy build: $(date +'%Y-%m-%dT%H:%M:%S%z')"
          git push origin build --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
